bool I2CreadInt(tSensors link, ubyte address, ubyte reg, int &retval, tByteArray request, tByteArray reply, bool msbfirst = true)
bool I2CreadLong(tSensors link, ubyte address, ubyte reg, int &retval, tByteArray request, tByteArray reply, bool msbfirst = true)
bool I2CreadSByte(tSensors link, ubyte address, ubyte reg, sbyte &retval, tByteArray request, tByteArray reply)
bool I2CreadUByte(tSensors link, ubyte address, ubyte reg, ubyte &retval, tByteArray request, tByteArray reply)
bool strtok(char *buffer, char *token, char *seperator)
bool waitForI2CBus(tSensors link)
bool writeI2C(tSensors link, tByteArray &request)
bool writeI2C(tSensors link, tByteArray &request, tByteArray &reply, int replylen)
long getUID()
void clearI2CError(tSensors link, ubyte address)
void clearI2Cbus(tSensors link)
