bool DGPSreadStatus(tSensors link)
bool DGPSsetDestination(tSensors link, long latitude, long longitude)
int DGPSreadDistToDestination(tSensors link)
int DGPSreadHeading(tSensors link)
int DGPSreadRelHeading(tSensors link)
int DGPSreadTravHeading(tSensors link)
int DGPSreadVelocity(tSensors link)
long DGPSreadLatitude(tSensors link)
long DGPSreadLongitude(tSensors link)
long DGPSreadUTC(tSensors link)
long _DGPSreadRegister(tSensors link, unsigned byte command, int replysize)
