bool DIMUconfigAccel(tDIMUdataPtr sensor, ubyte range)
bool DIMUconfigAccel(tSensors link, ubyte range)
bool DIMUconfigGyro(tDIMUdataPtr sensor, ubyte range, bool lpfenable)
bool DIMUconfigGyro(tDIMUdataPtr sensor, ubyte range, bool lpfenable=true)
bool DIMUconfigGyro(tSensors link, ubyte range, bool lpfenable)
bool DIMUconfigGyro(tSensors link, ubyte range, bool lpfenable=true)
bool DIMUconfigIMU(tDIMUdataPtr sensor, ubyte accelRange, ubyte gyroRange, bool lpfenable)
bool DIMUconfigIMU(tDIMUdataPtr sensor, ubyte accelRange=DIMU_ACC_RANGE_8G, ubyte gyroRange=DIMU_GYRO_RANGE_250, bool lpfenable=true)
bool DIMUconfigIMU(tSensors link, ubyte accelRange, ubyte gyroRange, bool lpfenable)
bool DIMUconfigIMU(tSensors link, ubyte accelRange=DIMU_ACC_RANGE_8G, ubyte gyroRange=DIMU_GYRO_RANGE_250, bool lpfenable=true)
bool DIMUsetAccelAxisOffset(tSensors link, ubyte drift_reg, ubyte drift_LSB, ubyte drift_MSB)
float DIMUreadAccelAxis10Bit(tSensors link, ubyte axis, bool calibrate = false)
float DIMUreadAccelAxis10Bit(tSensors link, ubyte axis, bool calibrate)
float DIMUreadAccelAxis8Bit(tSensors link, ubyte axis)
float DIMUreadGyroAxis(tSensors link, ubyte axis)
void DIMUcalAccel(tDIMUdataPtr sensor)
void DIMUcalAccel(tSensors link)
void DIMUreadAccelAxes10Bit(tDIMUdataPtr sensor)
void DIMUreadAccelAxes10Bit(tSensors link, float &_x, float &_y, float &_z)
void DIMUreadAccelAxes8Bit(tDIMUdataPtr sensor)
void DIMUreadAccelAxes8Bit(tSensors link, float &_x, float &_y, float &_z)
void DIMUreadGyroAxes(tDIMUdataPtr sensor)
void DIMUreadGyroAxes(tSensors link, float &_x, float &_y, float &_z)
