bool TIRresetSensor(tSensors link)
bool TIRsetEmissivity(tSensors link, int emissivity)
float TIRreadAmbientTemp(tSensors link)
float TIRreadObjectTemp(tSensors link)
long TIRcheckEmissivity(tSensors link)
long TIRreadEmissivity(tSensors link)
