int DFLEXvalNorm(tSensors link)
int DFLEXvalRaw(tSensors link)
void DFLEXcalHigh(int highval)
void DFLEXcalHigh(tSensors link)
void DFLEXcalLow(int lowval)
void DFLEXcalLow(tSensors link)
void _DFLEXcheckSensor(tSensors link)
void _DFLEXreadCalVals(int &lowval, int &highval)
void _DFLEXwriteCalVals(int lowval, int highval)
