bool HTPBreadAllADC(tMUXSensor muxsensor, int &adch0, int &adch1, int &adch2, int &adch3, int &adch4, byte width)
bool HTPBreadAllADC(tSensors link, int &adch0, int &adch1, int &adch2, int &adch3, int &adch4, byte width)
bool HTPBsetSamplingTime(tSensors link, byte interval)
bool HTPBsetupIO(tSensors link, ubyte mask)
bool HTPBwriteIO(tSensors link, ubyte mask)
int HTPBreadADC(tMUXSensor muxsensor, byte channel, byte width)
int HTPBreadADC(tSensors link, byte channel, byte width)
ubyte HTPBreadIO(tMUXSensor muxsensor, ubyte mask)
ubyte HTPBreadIO(tSensors link, ubyte mask)
