bool HTCScalWhite(tSensors link)
bool HTCSreadHSV(tMUXSensor muxsensor, float &hue, float &saturation, float &value)
bool HTCSreadHSV(tSensors link, float &hue, float &saturation, float &value)
bool HTCSreadNormRGB(tSensors link, int &red, int &green, int &blue)
bool HTCSreadRGB(tMUXSensor muxsensor, int &red, int &green, int &blue)
bool HTCSreadRGB(tSensors link, int &red, int &green, int &blue)
bool HTCSreadRawRGB(tSensors link, int &red, int &green, int &blue)
int HTCSreadColor(tMUXSensor muxsensor)
int HTCSreadColor(tSensors link)
int HTCSreadColorIndex(tSensors link)
