bool HTMCstartCal(tSensors link)
bool HTMCstopCal(tSensors link)
int HTMCreadHeading(tMUXSensor muxsensor)
int HTMCreadHeading(tSensors link)
int HTMCreadRelativeHeading(tMUXSensor muxsensor)
int HTMCreadRelativeHeading(tSensors link)
int HTMCsetTarget(tMUXSensor muxsensor, int offset = 0)
int HTMCsetTarget(tMUXSensor muxsensor, int offset)
int HTMCsetTarget(tSensors link, int offset = 0)
int HTMCsetTarget(tSensors link, int offset)
