bool HTRCXmotorFwd(tSensors link, unsigned byte _motor)
bool HTRCXmotorOff(tSensors link, unsigned byte _motor)
bool HTRCXmotorOn(tSensors link, unsigned byte _motor)
bool HTRCXmotorPwr(tSensors link, unsigned byte _motor, unsigned byte power)
bool HTRCXmotorRev(tSensors link, unsigned byte _motor)
bool HTRCXplaySound(tSensors link, unsigned byte sound)
bool HTRCXreadResp(tSensors link, tByteArray &response)
bool HTRCXsendByte(tSensors link, unsigned byte data)
bool HTRCXsendHeader(tSensors link)
bool HTRCXsendWord(tSensors link, short data)
void HTRCXencode(tSensors link, tByteArray &iBuffer, tByteArray &oBuffer)
