HTSMUXSensorType HTSMUXreadSensorType(tMUXSensor muxsensor)
bool HTSMUXconfigChannel(tMUXSensor muxsensor, tConfigParams &configparams)
bool HTSMUXreadPort(tMUXSensor muxsensor, tByteArray &result, int numbytes, int offset = 0)
bool HTSMUXreadPort(tMUXSensor muxsensor, tByteArray &result, int numbytes, int offset)
bool HTSMUXreadPowerStatus(tSensors link)
bool HTSMUXsendCommand(tSensors link, byte command)
bool HTSMUXsetAnalogueActive(tMUXSensor muxsensor)
bool HTSMUXsetAnalogueInactive(tMUXSensor muxsensor)
bool HTSMUXsetMode(tMUXSensor muxsensor, byte mode)
byte HTSMUXreadStatus(tSensors link)
int HTSMUXreadAnalogue(tMUXSensor muxsensor)
void HTSMUXsensorTypeToString(HTSMUXSensorType muxsensor, string &sensorName)
