bool HTANGresetAccumulatedAngle(tSensors link)
bool HTANGresetAngle(tSensors link)
bool _HTANGsendCommand(tSensors link, byte command)
int HTANGreadAngle(tMUXSensor muxsensor)
int HTANGreadAngle(tSensors link)
int HTANGreadRPM(tMUXSensor muxsensor)
int HTANGreadRPM(tSensors link)
long HTANGreadAccumulatedAngle(tMUXSensor muxsensor)
long HTANGreadAccumulatedAngle(tSensors link)
