int HTMAGreadCal(tMUXSensor muxsensor)
int HTMAGreadCal(tSensors link)
int HTMAGreadRaw(tMUXSensor muxsensor)
int HTMAGreadRaw(tSensors link)
int HTMAGreadVal(tMUXSensor muxsensor)
int HTMAGreadVal(tSensors link)
int HTMAGstartCal(tMUXSensor muxsensor)
int HTMAGstartCal(tSensors link)
void HTMAGsetCal(tMUXSensor muxsensor, int bias)
void HTMAGsetCal(tSensors link, int bias)
