bool HTCS2readHSV(tMUXSensor muxsensor, float &hue, float &saturation, float &value)
bool HTCS2readHSV(tSensors link, float &hue, float &saturation, float &value)
bool HTCS2readNormRGB(tSensors link, int &red, int &green, int &blue)
bool HTCS2readRGB(tMUXSensor muxsensor, int &red, int &green, int &blue)
bool HTCS2readRGB(tSensors link, int &red, int &green, int &blue)
bool HTCS2readRawRGB(tSensors link, bool passive, long &red, long &green, long &blue)
bool HTCS2readRawWhite(tSensors link, bool passive, long &white)
bool HTCS2readWhite(tSensors link, int &white)
bool _HTCSsendCommand(tSensors link, byte command)
int HTCS2readColor(tMUXSensor muxsensor)
int HTCS2readColor(tSensors link)
int HTCS2readColorIndex(tSensors link)
