bool HTIRS2readAllACStrength(tMUXSensor muxsensor, int &acS1, int &acS2, int &acS3, int &acS4, int &acS5)
bool HTIRS2readAllACStrength(tSensors link, int &acS1, int &acS2, int &acS3, int &acS4, int &acS5)
bool HTIRS2readAllDCStrength(tMUXSensor muxsensor, int &dcS1, int &dcS2, int &dcS3, int &dcS4, int &dcS5)
bool HTIRS2readAllDCStrength(tSensors link, int &dcS1, int &dcS2, int &dcS3, int &dcS4, int &dcS5)
bool HTIRS2readEnhanced(tMUXSensor muxsensor, int &dir, int &strength)
bool HTIRS2readEnhanced(tSensors link, int &dir, int &strength)
bool HTIRS2setDSPMode(tSensors link, tHTIRS2DSPMode mode)
int HTIRS2readACDir(tMUXSensor muxsensor)
int HTIRS2readACDir(tSensors link)
int HTIRS2readDCAverage(tMUXSensor muxsensor)
int HTIRS2readDCAverage(tSensors link)
int HTIRS2readDCDir(tMUXSensor muxsensor)
int HTIRS2readDCDir(tSensors link)
