bool HRWBconfigNetwork(tSensors link, tNetworkInfo &netInfo)
bool HRWBdisableWifi(tSensors link)
bool HRWBdoGET(tSensors link, tGetRequest &getrequest)
bool HRWBdoPOST(tSensors link, tPostRequest &postrequest)
bool HRWBdoTCP(tSensors link, tTCPRequest &tcprequest)
bool HRWBdoUDP(tSensors link, tUDPRequest &udprequest)
bool HRWBenableWifi(tSensors link)
bool HRWBeraseConfig(tSensors link)
bool HRWBreadBigReg(tSensors link, int reg, int size)
bool HRWBreadReg(tSensors link, int reg, int size)
bool HRWBresetWifiBlock(tSensors link)
bool HRWBsaveConfig(tSensors link)
bool HRWBscanChannel(tSensors link, ubyte channel)
bool HRWBscanWifi(tSensors link)
bool HRWBwriteReg(tSensors link, int reg, tBigByteArray &data, int size)
bool HRWBwriteReg(tSensors link, int reg, tByteArray &data, int size)
bool HRWBwriteReg(tSensors link, int reg, tHugeByteArray &data, int size)
bool HRWBwriteReg(tSensors link, int reg, ubyte data)
bool HRWBwriteRegMasked(tSensors link, int reg, ubyte data, ubyte mask)
bool _HRWBwriteRegPrivate(tSensors link, int reg, tByteArray &data, int size)
float HRWBreadBatt(tSensors link)
int HRWBreadHTTPCode(tSensors link)
int strsize(tHugeByteArray &array)
void stringToIp(const string address, tIPaddr &addr)
