bool USreadDistances(tSensors link, tByteArray &distances)
bool USreset(tSensors link)
bool USsetContinuousMode(tSensors link)
bool USsetEventCapture(tSensors link)
bool USsetOff(tSensors link)
bool USsetSingleMode(tSensors link)
bool _USsendCmd(tSensors link, ubyte command)
int USreadDist(tMUXSensor muxsensor)
int USreadDist(tSensors link)
