int LSvalNorm(tMUXSensor muxsensor)
int LSvalNorm(tSensors link)
int LSvalRaw(tMUXSensor muxsensor)
int LSvalRaw(tSensors link)
void LScalHigh(tMUXSensor muxsensor)
void LScalHigh(tSensors link)
void LScalLow(tMUXSensor muxsensor)
void LScalLow(tSensors link)
void LSsetActive(tMUXSensor muxsensor)
void LSsetActive(tSensors link)
void LSsetInactive(tMUXSensor muxsensor)
void LSsetInactive(tSensors link)
void _LScheckSensor(tSensors link)
void _LSreadCalVals()
void _LSwriteCalVals()
