bool LLcalBlack(tSensors link)
bool LLcalWhite(tSensors link)
bool LLinit(tSensors link)
bool LLinvertLineColor(tSensors link)
bool LLreadBlackThresh(tSensors link, tByteArray &pMsg)
bool LLreadSensorRaw(tSensors link, tByteArray &pMsg)
bool LLreadWhiteThresh(tSensors link, tByteArray &pMsg)
bool LLresetLineColor(tSensors link)
bool LLsetKd(tSensors link, ubyte data, ubyte factor)
bool LLsetKi(tSensors link, ubyte data, ubyte factor)
bool LLsetKp(tSensors link, ubyte data, ubyte factor)
bool LLsetPoint(tSensors link, ubyte data)
bool LLsleep(tSensors link)
bool LLtakeSnapshot(tSensors link)
bool LLwakeUp(tSensors link)
bool _lineLeader_cmd(tSensors link, ubyte cmd)
bool _lineLeader_read(tSensors link, ubyte regToRead, int numBytes, tByteArray &pDataMsg)
bool _lineLeader_read(tSensors link, ubyte regToRead, ubyte &retval)
bool _lineLeader_write(tSensors link, ubyte regToWrite, ubyte data)
int LLreadAverage(tSensors link)
int LLreadKd(tSensors link)
int LLreadKdFactor(tSensors link)
int LLreadKi(tSensors link)
int LLreadKiFactor(tSensors link)
int LLreadKp(tSensors link)
int LLreadKpFactor(tSensors link)
int LLreadResult(tSensors link)
int LLreadSteering(tSensors link)
int LLsetPoint(tSensors link)
