bool MSPMreadVoltageCurrent(tSensors link, int &voltage, int &current, ubyte address = MSPM_I2C_ADDR)
bool MSPMreadVoltageCurrent(tSensors link, int &voltage, int &current, ubyte address)
bool MSPMresetCounters(tSensors link, ubyte address = MSPM_I2C_ADDR)
bool MSPMresetCounters(tSensors link, ubyte address)
bool _MSPMsendCommand(tSensors link, byte command, ubyte address)
int MSPMreadCurrent(tSensors link, ubyte address = MSPM_I2C_ADDR)
int MSPMreadCurrent(tSensors link, ubyte address)
int MSPMreadVoltage(tSensors link, ubyte address = MSPM_I2C_ADDR)
int MSPMreadVoltage(tSensors link, ubyte address)
long MSPMreadTime(tSensors link, ubyte address = MSPM_I2C_ADDR)
long MSPMreadTime(tSensors link, ubyte address)
