bool MSDISTsendCmd(tSensors link, byte command, ubyte address = MSDIST_I2C_ADDR)
bool MSDISTsendCmd(tSensors link, byte command, ubyte address)
int MSDISTreadDist(tSensors link, ubyte address = MSDIST_I2C_ADDR)
int MSDISTreadDist(tSensors link, ubyte address)
int MSDISTreadMaxDist(tSensors link, ubyte address = MSDIST_I2C_ADDR)
int MSDISTreadMaxDist(tSensors link, ubyte address)
int MSDISTreadMinDist(tSensors link, ubyte address = MSDIST_I2C_ADDR)
int MSDISTreadMinDist(tSensors link, ubyte address)
int MSDISTreadModuleType(tSensors link, ubyte address = MSDIST_I2C_ADDR)
int MSDISTreadModuleType(tSensors link, ubyte address)
int MSDISTreadVoltage(tSensors link, ubyte address = MSDIST_I2C_ADDR)
int MSDISTreadVoltage(tSensors link, ubyte address)
