void PIDCompute()
void PIDInitialize()
void PIDSetControllerDirection(int Direction)
void PIDSetMode(int Mode)
void PIDSetOutputLimits(float Min, float Max)
void PIDSetSampleTime(int NewSampleTime)
void PIDSetTunings(float Kp, float Ki, float Kd)
